name: task_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  table_calendar: ^3.1.2
  dropdown_button2: ^2.3.9
  firebase_auth: ^5.3.0
  logger: ^2.4.0
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.8.0
  flutter_local_notifications: ^17.2.3
  pie_chart: ^5.4.0
  fl_chart: ^0.63.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/